apiVersion: v1
kind: pod
metadata:
  name:
  labels:
    name: 
    app: pod-app
spec:
  containers:
    name: 
    image:
    ports:
      - containerPort: 80
    envFrom:
      - name: frontend
        valueFrom:
          SecretKeyRef:
           name:
           key:
